# Cloud Build設定ファイル - AI人狼オンライン

steps:
  # バックエンドのDockerイメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/werewolf-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/werewolf-backend:latest'
      - '-f'
      - 'backend/Dockerfile.cloudrun'
      - './backend'
    waitFor: ['-']

  # フロントエンドのDockerイメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/werewolf-frontend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/werewolf-frontend:latest'
      - '-f'
      - 'frontend/Dockerfile.cloudrun'
      - './frontend'
    waitFor: ['-']

  # バックエンドイメージをContainer Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/werewolf-backend:$COMMIT_SHA'
    waitFor: ['build-backend']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend-latest'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/werewolf-backend:latest'
    waitFor: ['build-backend']

  # フロントエンドイメージをContainer Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/werewolf-frontend:$COMMIT_SHA'
    waitFor: ['build-frontend']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend-latest'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/werewolf-frontend:latest'
    waitFor: ['build-frontend']

  # Cloud SQL Proxyでデータベースマイグレーション実行
  - name: 'gcr.io/cloud-sql-docker/gce-proxy:1.33.14'
    id: 'db-migration'
    args:
      - '/cloud_sql_proxy'
      - '-instances=$PROJECT_ID:asia-northeast1:werewolf-db=tcp:5432'
      - '&'
      - 'sleep'
      - '10'
      - '&&'
      - 'python'
      - 'database/migrate.py'
    env:
      - 'DATABASE_URL=postgresql://werewolf_user:$$DB_PASSWORD@localhost:5432/werewolf_game'
    secretEnv: ['DB_PASSWORD']
    waitFor: ['push-backend']

  # バックエンドをCloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'werewolf-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/werewolf-backend:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_REGION=asia-northeast1,ENVIRONMENT=production'
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest,REDIS_URL=REDIS_URL:latest'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:asia-northeast1:werewolf-db'
    waitFor: ['push-backend', 'db-migration']

  # フロントエンドをCloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'werewolf-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/werewolf-frontend:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '5'
      - '--concurrency'
      - '100'
      - '--timeout'
      - '60'
      - '--set-env-vars'
      - 'BACKEND_URL=https://werewolf-backend-RANDOM-HASH-an.a.run.app'
    waitFor: ['push-frontend', 'deploy-backend']

# 秘密情報の設定
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
      env: 'DATABASE_URL'
    - versionName: projects/$PROJECT_ID/secrets/REDIS_URL/versions/latest
      env: 'REDIS_URL'
    - versionName: projects/$PROJECT_ID/secrets/DB_PASSWORD/versions/latest
      env: 'DB_PASSWORD'

# ビルド設定
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

# タイムアウト設定
timeout: '1800s'

# タグ設定
tags:
  - 'werewolf-game'
  - 'cloud-run'
  - 'production'