apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: werewolf-backend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
    autoscaling.knative.dev/minScale: "0"
    autoscaling.knative.dev/maxScale: "10"
    run.googleapis.com/cpu-throttling: "false"
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu: "1"
        run.googleapis.com/memory: "4Gi"
        run.googleapis.com/vpc-access-connector: "werewolf-connector"
        run.googleapis.com/vpc-access-egress: "private-ranges-only"
        run.googleapis.com/cloudsql-instances: "PROJECT_ID:asia-northeast1:werewolf-db"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: werewolf-backend-sa@PROJECT_ID.iam.gserviceaccount.com
      containers:
      - image: gcr.io/PROJECT_ID/werewolf-backend:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: GOOGLE_CLOUD_PROJECT
          value: "fourth-dynamo-423103-q2"
        - name: GOOGLE_CLOUD_REGION
          value: "asia-northeast1"
        - name: GOOGLE_PROJECT_ID
          value: "fourth-dynamo-423103-q2"
        - name: GOOGLE_LOCATION
          value: "asia-northeast1"
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-url
              key: latest
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-url
              key: latest
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret-key
              key: latest
        resources:
          limits:
            cpu: "1"
            memory: "4Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10