version: '3.8'

services:
  # Development Database
  database:
    image: postgres:15-alpine
    container_name: werewolf_db_dev
    environment:
      POSTGRES_DB: werewolf_game_dev
      POSTGRES_USER: werewolf_user
      POSTGRES_PASSWORD: werewolf_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U werewolf_user -d werewolf_game_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Development Redis
  redis:
    image: redis:7-alpine
    container_name: werewolf_redis_dev
    ports:
      - "6380:6379"
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Backend Development (with hot reload)
  backend-dev:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
      target: development
    container_name: werewolf_backend_dev
    environment:
      - DATABASE_URL=postgresql://werewolf_user:werewolf_password@database:5432/werewolf_game_dev
      - REDIS_URL=redis://redis:6379
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - GOOGLE_CLOUD_REGION=${GOOGLE_CLOUD_REGION:-asia-northeast1}
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173
      - LOG_LEVEL=DEBUG
      - ENVIRONMENT=development
    ports:
      - "8001:8000"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ~/.config/gcloud:/home/appuser/.config/gcloud:ro
    command: ["python", "-m", "watchdog", "game_logic/main.py"]

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local